version: "3"

# All available services
services:

  # Misc Storage
  postgres:
    container_name: "metabase-postgres-container"
    restart: "always"
    image: postgres
    env_file:
      - ./config/postgres.config
    volumes:
      - data:/var/lib/postgresql/data/
      - ./services/postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 54320:5432

  metabase:
    container_name: "metabase-container"
    restart: "always"
    image: metabase/metabase
    env_file:
      - ./config/metabase.config
    ports:
      - 8123:3000

# Volumes to persist data
volumes:
  data:
